# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Joshua Ching
email: jchin060@uottawa.ca
description: > # this means to ignore newlines until "baseurl:"
  I am an undergraduate student studying Biomedical Mechanical Engineering and
  Computing Technology in the University of Ottawa.
baseurl: "" # the subpath of your site, e.g. /blog
url: "chingjoshua.github.io" # the base hostname & protocol for your site
twitter_username: N/A
github_username:  ChingJoshua

# Build settings
markdown: kramdown
